language: java
jdk:
  - oraclejdk8
before_script:
  - if [ ! -z "$TRAVIS_TAG" ]; then mvn versions:set -DnewVersion=$TRAVIS_TAG; fi
script:
  - mvn clean install
after_success:
  - bash <(curl -s https://codecov.io/bash)
