language: java
jdk:
- oraclejdk8
before_script:
- if [ ! -z "$TRAVIS_TAG" ]; then mvn versions:set -DnewVersion=$TRAVIS_TAG; fi
script:
- mvn clean install
after_success:
- bash <(curl -s https://codecov.io/bash)
- if [ -z "$TRAVIS_TAG" ]; then mvn deploy -B -DskipTests=true --settings settings.xml; fi
deploy:
  provider: releases
  api_key:
    secure: VauCVKIBFGf81FIAWklZ1icVbra45UlgeyO5ZV5p64rBUXjoDLG7biEhLwgoSrhvsOE/iYKBMBI80GeVjVVj9C5vInXCf/723tnYV6FI37tsXuAeZrzGUombuRNsT6J8r5RMboa6XBSdDZRd8Fov9Ca47yQG0s1uAwdQ3DE/XnwfLRnJUQQutmFBQj6BLB5pfWt4yNHvNLt7DkxKJq/hZLk19jPFqVAM/NeawYp9raHVRgfGhepIJTJxg2lUjyZGqVJ+ntCAxKMuItfT5HJvNsR8VLzx+ajOOmzP/r15QPbOr6AswRcl3pgYtSrMLQh6a1ntjZnIUW9UrNRHJQ6og43Uh8FBilzljyDHTRScFEghkh4aIHKsiXLdJHiG0PKJ4Kog2hnmVO3eFUrXNvM8l5hJEiIOmAhdr4bszls0cfTw/l5mzJjh6erMwMidgkXx2yutqvj1qkvWLl9JgNKfuMTKuqo9jBwUgTdXu3z7m4baps5U1aCf0jWNgchXSFnz8nNRdDtdhD7cRWK13Sgv62ZXsYYoM59ij+qibefIRrxwF2FNDavoy/IhHIMc5Xbq0OiPFsn189ouo64Gd+fpsuwUfUkuHQlbLNXOjEj1qJ+Q4eP0QfQpQ7SIoctGrxL726nIu0HjlMEwmM25hGMNoKRGhYoX3C/+iZuRZWB1Zqw=
  file_glob: true
  file:
  - "**/target/*.jar"
  skip_cleanup: true
  on:
    tags: true
env:
  global:
  - secure: YxmflqrPhRUb3d8bM5SEB7JIhQ0wKyrqIApC7/rIzyAyV9qQ7Cq8eQvH7574OiYWWQBFdoH1ajrAC0ClV058HUDhrUlxWPxn2A6B+hu1ThSzfeLsozcGdJ95Dwzmz/3mDVz5mMngfg3+GLfSXYlmqs2fiVcvnVxDwAT8e3KY66WgVieUT+7zAQ/VD23feyuHKpnRch+i4Lj9gU08UhSCkl5ErRhR38ja/MR9eIH4tsxt83qDN6VTXUDiTvfTetKXZrb5I+o3X7XUUkxnACi232vVK6UORgBbzCFV2lM1H3xXU2Yw3JeHvqeELAeW1RtBehEwfDcq/18YTLYo+7SUCRxdhNBknvtEyXsHbTySNtBSQw33gOQz4ztrHns+rVcbGWYaxhakvWmtdqm3dnBdCkx94r8BMZUSONZPxNi85dftk/grVUPsLyLyZzM6gjvuq3B6+wnIGeIDMTI3QzlxfUwZoPkiLvlGNaJ3vF4WHLhEbOiOfUOJGjMCGQwqX10/8vvZEx6j+L8Gy+DN9toOJhk2eAOBc7Fzqlixwg5OglEFDI9Y8u4KoHpf6OYtZ8hJXBRR0mKeaP/ngQBJrVk6pb9r/ebfQZNdHPKd+tDztiPcDWrfA2kaU61t1MDw2gA8RF7+T2x6SZPvc/BzrImKwsmpyfDOsX1reB1kTYJuClw=
  - secure: AEJU3eNXfYcSBtSjN60Prv/q9Pq/ByKNzXczPMOP0lQ4fNpwIZspK9yRLeWnF9kroTVIdq/PFGuG5MK+vQMh3e7F382KM2EEESTZbUGlJDiE9YVWI00+pZ5RVc0ZiK6rronM2MqpEwdTiseFlEgFyIfOIhKqfMNwObM4eUaMrnZJSvvgBWkFj0tW57rp6UrLi7asfZwUnVhcidiARPEVb1+wp92Z5XKJEuTgn6V1TP1qyM/JXUp0ysXSss11e94XPqehTvhRTHX3PORQofXjTyX6JTYzLnPJ5bHxUFL3hXSEY+4eb7mhVyefKlhYYhxfPIp6qK0mYoFMdW1QQle18GOqNYU6w3XAY7cMwlSAr3pdJBQDMwBcZsSo/uZzN+W6+qajOwC3LgMO78aNSz0bnB6b1+DlZpP7/gNRKVlMNU4bhL9VeWfFP6spVgQvkjUmd6lzyFveXpCtNYpZIFaEIOnnaMSrap0f6Y1BVFyXWHWjnhcOYf3B1bCgOFKp1es0wNBDhUx4x4X1JaEfBjT/8vIal3tRquTzTTjfdc5ZRQOYWDJXA1ibE2lcEmXhFdfux4+ih71jqtS/ltfZ4+fsJzN0+ATptBKW8FOnfMV+rsza+CaBQW5sTuIyB8PUlxOvc+gey27lcR26oYIZ7rPIrMbvT5mQ4tUjNlpeijCJhVI=
