language: java
jdk:
- oraclejdk8
before_script:
- if [ ! -z "$TRAVIS_TAG" ]; then mvn versions:set -DnewVersion=$TRAVIS_TAG; fi
script:
- mvn clean install
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  api_key:
    secure: VauCVKIBFGf81FIAWklZ1icVbra45UlgeyO5ZV5p64rBUXjoDLG7biEhLwgoSrhvsOE/iYKBMBI80GeVjVVj9C5vInXCf/723tnYV6FI37tsXuAeZrzGUombuRNsT6J8r5RMboa6XBSdDZRd8Fov9Ca47yQG0s1uAwdQ3DE/XnwfLRnJUQQutmFBQj6BLB5pfWt4yNHvNLt7DkxKJq/hZLk19jPFqVAM/NeawYp9raHVRgfGhepIJTJxg2lUjyZGqVJ+ntCAxKMuItfT5HJvNsR8VLzx+ajOOmzP/r15QPbOr6AswRcl3pgYtSrMLQh6a1ntjZnIUW9UrNRHJQ6og43Uh8FBilzljyDHTRScFEghkh4aIHKsiXLdJHiG0PKJ4Kog2hnmVO3eFUrXNvM8l5hJEiIOmAhdr4bszls0cfTw/l5mzJjh6erMwMidgkXx2yutqvj1qkvWLl9JgNKfuMTKuqo9jBwUgTdXu3z7m4baps5U1aCf0jWNgchXSFnz8nNRdDtdhD7cRWK13Sgv62ZXsYYoM59ij+qibefIRrxwF2FNDavoy/IhHIMc5Xbq0OiPFsn189ouo64Gd+fpsuwUfUkuHQlbLNXOjEj1qJ+Q4eP0QfQpQ7SIoctGrxL726nIu0HjlMEwmM25hGMNoKRGhYoX3C/+iZuRZWB1Zqw=
  file_glob: true
  file: "**/target/*.jar"
  skip_cleanup: true
  on:
    tags: true
